### ISSUE TITLE
Confirm support for all UAVs

### ISSUE THREAD

**Issue by alexcroox** [alexcroox/R3#12]
Originally reported by @theYoursTruly [here](https://github.com/alexcroox/R3-Web/issues/2), while the UAV he listed has been added, @tupolov highlighted that the 03/04 UAVs (DLC UAVs?) do not inherit from helicopter/plane base classes. Support for UAV base class will need to be added and tested.

**Comment by BryanBoru** [comment]
For reference:

- the [UAV_03](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_WEST#B_T_UAV_03_F) is the [MQ-12 Falcon](http://armedassault.wikia.com/wiki/MQ-12_Falcon) rotary UAV which came with the APEX Expansion. 
- To the best of my knowledge, there is not "UAV 04" but you are likely referring to [UGV_01](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_WEST#B_UGV_01_F) the [UGV Stomper](http://armedassault.wikia.com/wiki/UGV_Stomper) which is a vanilla ground based Autonomous vehicle. 
- I do not know how they set up the configs for the UGV at the moment, but a look over on the CfgVehicle in the [AllInOne](https://forums.bistudio.com/topic/191737-updated-all-in-one-config-dumps/#comment-3046042) or config browser should reveal it.
- Will add a replay if I get to look it over soon.

**Comment by alexcroox** [comment]
Cheers for info, UAV 4 is definitely a thing, it's the `KH-3A Fenghuang` https://configs.arma3.ru/162.137494/configFile/CfgVehicles/UAV_04_base_F.html

I'll add them to my test mission and get them logging

**Comment by alexcroox** [comment]
The good news is they do actually inherit from helicopter or plane so they get logged fine already. The bad news is the map icons are in `.ebo` files and I don't know how to extract them so I'll have to clone the vanilla drone icons :(

https://titanmods.xyz/r3/ark/356?force

**Comment by BryanBoru** [comment]
> UAV 4 is definitely a thing, it's the KH-3A Fenghuang https://configs.arma3.ru/162.137494/configFile/CfgVehicles/UAV_04_base_F.html

Ah ha. An APEX vehicle, makes sense. I was ignorant of it. Cheers! Glad the UGV worked out, was speculative that a PLANE class was parent somewhere or something Bohem.. I mean silly. :)

**Comment by alexcroox** [comment]
The UGVs inherit from car class so they appear as cars currently, hopefully someone will submit a UGV icon to the new system!

**Comment by BryanBoru** [comment]
I tried to but honestly I am having issue with Pal2Pac at this time. It's worked for me in other uses, but getting the 32x32 icon has proved frustrating. Both UGV version map Icons sit at x\a3\drones_f\soft_f_gamma\ugv_01\data\ui\ yet I simply can not get 32x icons without having the resize a PAA conversion myself

**Comment by alexcroox** [comment]
I put some instructions on the wiki and web repo README last night if it helps

https://github.com/alexcroox/R3-Web/wiki/Adding-new-icons

**Comment by BryanBoru** [comment]
I saw them, just can't seem to get Pal2Pac to work for me, I am sure it is user error.

**Comment by alexcroox** [comment]
Even after running the command in point 8). ?

**Comment by BryanBoru** [comment]
yep, I am certain I am doing something wrong, but I am heading out to work but I will try again tomorrow when home.
