### ISSUE TITLE
Running server as user SYSTEM / multiple servers

### ISSUE THREAD

**Issue by Arcanum417** [alexcroox/R3#16]
Where should i put config.properties if I am running servers as SYSTEM (windows) ?
Also  if I am running multiple servers using the same @ file and same user, is that ok ?

**Comment by kami-** [comment]
It has to be in the `%AppData%\Local\R3Extension` folder. For SYSTEM user it should be in either `C:\Windows\System32\config\systemprofile\AppData\Loca\R3Extension` or 
`C:\Windows\SysWOW64\config\systemprofile\AppData\Local\R3Extension`. Not sure wich one, you will have to test it.

As for multiple servers, we have not tested it, but I think it should work.

**Comment by kami-** [comment]
I have pushed a new version. You can now set the folder where R3 will search for the config using the `R3_EXTENSION_HOME` environment variable.

This means that now you can set separate config folders for each server.

**Comment by Arcanum417** [comment]
Well I am running all servers as one user so...

**Comment by alexcroox** [comment]
You should be fine with one config folder and one config for all your servers, follow the instructions in the first reply to your issue and you'll be good to go.

**Comment by Arcanum417** [comment]
Ok if that is the case I already have a working addon component, thanks. Will test with multiple servers in the future and keep you posted.
