### ISSUE TITLE
Package for steam workshop

### ISSUE THREAD

**Issue by mr-bo-jangles** [alexcroox/R3#18]
This would be really useful for people like me who have all their mods + deps installed/updated onto their server via the steam workshop.

**Comment by alexcroox** [comment]
I always thought installing STEAM mods on the server was a PITA, happy to put the next big version (being developed [in this branch](https://github.com/alexcroox/R3/tree/data-refactor)) on STEAM if it helps! You'll still need to follow the other installation instructions manually however.

**Comment by mr-bo-jangles** [comment]
That's fine, I'll package this version for my community for now (unless that's releasing shortly) the other aspects are not an issue :+1:

**Comment by mr-bo-jangles** [comment]
also re:steam mods on server being a pain, I've actually scripted the process very successfully for linux

**Comment by alexcroox** [comment]
Yer no problem, the new version won't be released for another couple of months I've got an enormous amount left to do on the playback and the whole install/update process I have planned for the web application part.

**Comment by alexcroox** [comment]
This is now on the workshop http://steamcommunity.com/sharedfiles/filedetails/?id=1093193732
