### ISSUE TITLE
[QUESTION] Compatible with Rented Servers?

### ISSUE THREAD

**Issue by byjokese** [alexcroox/R3#21]
Is this compatible with rented sever (like nitrado) where we don't have access to full system directory?

Is it data refactor released already? I see on the readme the NOTE, but not sure if is done yet or not.

Thanks.

**Comment by alexcroox** [comment]
In this commit https://github.com/alexcroox/R3/commit/2be6f7bc01a891785b60fcb652b1a42a10b386ce kami added support for putting the config file in the Arma server working directory for those that cannot access the rest of the file system. It's not been built yet however, I'll try get a release out this weekend with that change.

**Comment by alexcroox** [comment]
The data refactor hasn't been released yet, got seriously delayed due to a freelance project that came up. However another unit has offered to help get me test data soon so I should be able to continue soon. But don't hold your breath for a release anytime soon, so feel free to continue using the current build, it works fine.

**Comment by byjokese** [comment]
OK Thanks you so much for the info. Keep up the good work.

**Comment by alexcroox** [comment]
OK I tested this tonight, unfortunately it will only pick up the config file from the directory the script that boots the arma server is run from. On a rented slot server you will have even less access to that than you would the arma root directory, so it won't work unfortunately :( Sorry for getting your hopes up. Kami has suggested a potential future work around but it's quite involved at this time so isn't going to be on our radar anytime soon :(

**Comment by byjokese** [comment]
Ok Thanks for the quick testing and the info. I will have to find another solution for an AAR in rented servers.

Will keep an eye on your development.
