### ISSUE TITLE
Readme Error on 'Install Windows Server' Step 3.

### ISSUE THREAD

**Issue by byjokese** [alexcroox/R3#22]
On the [Readme.md](https://github.com/alexcroox/R3/blob/master/README.md) the section [**Install Windows Server**](https://github.com/alexcroox/R3#install-windows-server), on the step _3._ links to non existing file (404). 

I think since you moved the extension to other repository ([R3-Extension](https://github.com/alexcroox/R3-Extension)), the link should be: [https://github.com/alexcroox/R3-Extension/blob/master/config.properties](https://github.com/alexcroox/R3-Extension/blob/master/config.properties)

**Comment by alexcroox** [comment]
Good spot thank you!
